export enum FormDialogNames {
	AttendanceFormDialogComponent,
	MaterialFormDialogComponent,
	OrderFormDialogComponent,
	NoteFormDialogComponent,
	EmployeeFormDialogComponent,
	ClientFormDialogComponent,
	ClientTypeFormDialogComponent,
	ServiceFormDialogComponent,
	ServiceTypeFormDialogComponent,
	ServicePricePerClientFormDialogComponent,
	feedbackFormDialogComponent,
	incomeOutcomeFormDialogComponent,
	materialTrackingFormDialogComponent,
	orderTransactionFormDialogComponent,
	orderDetailsDialogComponent,
}
